---
- name: Localenv Playbook
  hosts: all
  vars:
    ##########
    ## The altbier_localenv role is controlled by variables
    ## The following variables are used
    ##########
    #
    ##########
    ## By default these are set to True
    ##########
    #
    ## Custom Color Prompt if set to True
    # altbier_localenv_custom_color_prompt: True
    #
    ## Install EPEL if set to True
    # altbier_localenv_epel_install: True
    #
    ## Package Update if set to True
    #altbier_localenv_pkg_update: True
    #
    ## Install Quality of Life Packages if set to True
    # altbier_localenv_pkgs_qol_install: True
    #
    ##########
    ## By default these are set to False
    ##########
    #
    ## Install Build Packages if set to True
    # altbier_localenv_pkgs_build_install: False
    #
    ## Install PuTTy Package from source if set to True
    # altbier_localenv_pkgs_putty_install: False
    #
    ## Install Ansible Packages if set to True
    # altbier_localenv_pkgs_ansible_install: False
    #
    # Resize local VM partition & filesystem if set to True
    # altbier_localenv_resize_disk: False
    #
    # Resize LVM & filesystem on RHEL in Azure if set to True
    # altbier_localenv_resize_az_rhel_lvm_disk: False
    #
  tasks:
  - name: Import role altbier_localenv
    ansible.builtin.import_role:
      name: altbier_localenv
